# Generated by Django 5.0.2 on 2024-03-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('foot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('ccountry', models.CharField(max_length=150)),
                ('ccompetitions', models.CharField(max_length=150)),
                ('cadress', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chemnaFC.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stadium', models.CharField(max_length=200)),
                ('club_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chemnaFC.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('pfoot', models.CharField(max_length=50)),
                ('prating', models.FloatField()),
                ('pposition', models.ManyToManyField(to='chemnaFC.position')),
            ],
        ),
    ]
