# Generated by Django 5.0.2 on 2024-03-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0002_remove_squad_pfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('played', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('club_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chemnaFC.clubs')),
            ],
        ),
    ]
