# Generated by Django 5.0.2 on 2024-03-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
