# Generated by Django 5.0.2 on 2024-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0004_alter_table_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='played',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
