# Generated by Django 5.0.2 on 2024-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0006_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fans',
            name='fan_level',
            field=models.CharField(choices=[('C', 'level3'), ('B', 'level2'), ('A', 'Topfan')], max_length=1),
        ),
    ]
