# Generated by Django 5.0.2 on 2024-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0007_alter_fans_fan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='fan_picture',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
