# Generated by Django 5.0.2 on 2024-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0008_fans_fan_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fans',
            name='fan_picture',
            field=models.FileField(upload_to='images'),
        ),
    ]
