# Generated by Django 5.0.2 on 2024-03-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0009_alter_fans_fan_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fans',
            name='fan_picture',
        ),
    ]
