# Generated by Django 5.0.2 on 2024-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0010_remove_fans_fan_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_picture', models.FileField(upload_to='profilePicture')),
            ],
        ),
    ]
