# Generated by Django 5.0.2 on 2024-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0011_fanpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpicture',
            name='fan_picture',
            field=models.FileField(upload_to='images'),
        ),
    ]
