# Generated by Django 5.0.2 on 2024-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnaFC', '0013_alter_fanpicture_fan_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='fan_picture',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
